# Generated by Django 5.1.5 on 2026-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_session_70d41b_idx',
            old_name='chat_chatme_session_d2d611_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_chatse_user_id_47c665_idx',
            old_name='chat_chatses_user_id_2c2e5e_idx',
        ),
    ]
