# Generated by Django 5.1.5 on 2026-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_user_id_55b4e4_idx',
            old_name='applicatio_user_id_2ad9c9_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_user_id_19c344_idx',
            old_name='applicatio_user_id_800f17_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_company_3fae95_idx',
            old_name='applicatio_company_33bfc1_idx',
        ),
    ]
