# Generated by Django 5.1.5 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_applicatio_user_id_2ad9c9_idx_application_user_id_55b4e4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0, help_text='Match Score (0-100)'),
        ),
    ]
