# Generated by Django 5.1.5 on 2026-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='jobs_jobdes_user_id_a9da7d_idx',
            old_name='jobs_jobdes_user_id_c8dc58_idx',
        ),
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='jobs_jobdes_company_88bd8c_idx',
            old_name='jobs_jobdes_company_95e65f_idx',
        ),
    ]
