# Generated by Django 5.1.5 on 2026-02-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_jobdes_user_id_c8dc58_idx_jobs_jobdes_user_id_a9da7d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='apply_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
