# Generated by Django 5.1.5 on 2026-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='skill_gaps',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='match_score',
            field=models.IntegerField(default=0, help_text='Match Score (0-100)'),
        ),
    ]
