# Generated by Django 5.1.5 on 2026-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_remove_analysisresult_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='improvement_suggestions',
            field=models.JSONField(default=list),
        ),
    ]
