# Generated by Django 5.1.5 on 2026-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_res_user_id_6019d7_idx',
            old_name='resumes_res_user_id_923ebe_idx',
        ),
    ]
